language: bash

sudo: required

services:
  - docker

env:
  global:
    - NGINX_VERSION=1.16.0
  matrix:
##    5.6
    - VERSION=5.6 VARIANT=nginx PHP_VERSION=5.6.40
##    7.0
    - VERSION=7.0 VARIANT=nginx PHP_VERSION=7.0.33
##    7.1
    - VERSION=7.1 VARIANT=nginx PHP_VERSION=7.1.28
##    7.2
    - VERSION=7.2 VARIANT=nginx PHP_VERSION=7.2.17
##    7.3
    - VERSION=7.3 VARIANT=nginx PHP_VERSION=7.3.4

before_install:
  - export DOCKER_COMPOSE_VERSION=1.24.0
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

before_script:
  - env | sort
  - image="larvacent/php:${VERSION}-${VARIANT}"

script:
  - travis_retry docker build --build-arg PHP_VERSION=${PHP_VERSION} --build-arg NGINX_VERSION=${NGINX_VERSION} -t "$image" .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login --username="${DOCKER_REGISTRY_USER}" --password="${DOCKER_REGISTRY_PASSWORD}";
      docker push $image;
      docker tag $image larvacent/php:${PHP_VERSION}-${VARIANT};
      docker push larvacent/php:${PHP_VERSION}-${VARIANT};
      if [ "${VERSION}" == "7.2" ]; then
        docker tag $image larvacent/php:latest;
        docker push larvacent/php:latest;
        docker tag $image larvacent/php:${PHP_VERSION};
        docker push larvacent/php:${PHP_VERSION};
        docker tag $image larvacent/php:${VERSION};
        docker push larvacent/php:${VERSION};
      fi
    fi

# vim:set et ts=2 sw=2:
